<?php
/**
 * CreateUserScheduleRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Feed API
 *
 * The Feed API lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.
 *
 * OpenAPI spec version: v1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateUserScheduleRequestTest Class Doc Comment
 *
 * @category    Class
 * @description The type that defines the fields for the &lt;strong&gt;createSchedule&lt;/strong&gt; method.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateUserScheduleRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateUserScheduleRequest"
     */
    public function testCreateUserScheduleRequest()
    {
    }

    /**
     * Test attribute "feed_type"
     */
    public function testPropertyFeedType()
    {
    }

    /**
     * Test attribute "preferred_trigger_day_of_month"
     */
    public function testPropertyPreferredTriggerDayOfMonth()
    {
    }

    /**
     * Test attribute "preferred_trigger_day_of_week"
     */
    public function testPropertyPreferredTriggerDayOfWeek()
    {
    }

    /**
     * Test attribute "preferred_trigger_hour"
     */
    public function testPropertyPreferredTriggerHour()
    {
    }

    /**
     * Test attribute "schedule_end_date"
     */
    public function testPropertyScheduleEndDate()
    {
    }

    /**
     * Test attribute "schedule_name"
     */
    public function testPropertyScheduleName()
    {
    }

    /**
     * Test attribute "schedule_start_date"
     */
    public function testPropertyScheduleStartDate()
    {
    }

    /**
     * Test attribute "schedule_template_id"
     */
    public function testPropertyScheduleTemplateId()
    {
    }

    /**
     * Test attribute "schema_version"
     */
    public function testPropertySchemaVersion()
    {
    }
}
