<?php
/**
 * CreateOrderTaskRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Feed API
 *
 * The Feed API lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.
 *
 * OpenAPI spec version: v1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.18
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateOrderTaskRequestTest Class Doc Comment
 *
 * @category    Class
 * @description The type that defines the fields for the &lt;b&gt; createOrderTask&lt;/b&gt; request.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOrderTaskRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateOrderTaskRequest"
     */
    public function testCreateOrderTaskRequest()
    {
    }

    /**
     * Test attribute "feed_type"
     */
    public function testPropertyFeedType()
    {
    }

    /**
     * Test attribute "filter_criteria"
     */
    public function testPropertyFilterCriteria()
    {
    }

    /**
     * Test attribute "schema_version"
     */
    public function testPropertySchemaVersion()
    {
    }
}
